# Generated by Django 5.2.5 on 2025-09-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit_shop', '0002_declaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Apple', 'Apple'), ('Banana', 'Banana'), ('Pineapple', 'Pineapple'), ('Peach', 'Peach')], max_length=50, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')])),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Error', 'Error')], default='Success')),
                ('quantity', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruit_shop.fruit')),
            ],
        ),
    ]
